rabbit1:
  image: cyrilix/rabbitmq-mqtt
  hostname: rabbitmqtt
  ports:
    - "1883:1883"
    - "8883:8883"
    - "15672:15672"
  environment:
    - RABBITMQ_DEFAULT_USER=user
    - RABBITMQ_DEFAULT_PASS=123456
