version: '2' 
services:
 elasticsearch:
  image: elasticsearch
  environment:
   - cluster.name=elasticsearch
  hostname: elasticsearch
  ports:
   - "9200:9200"
 kibana:
  image: kibana
  environment:
   SERVER_NAME: kibana
   ELASTICSEARCH_URL: http://elasticsearch:9200
  ports:
   - "5601:5601"
